apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels: 
        app: {{ .Values.appName }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.ImagePullSecret }}
      containers:
      - name: {{ .Values.appName }}
        image: {{ .Values.imageName }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        # livenessProbe:
        #   httpGet:
        #     path: "/health"
        #     port: {{ .Values.containerPort }}
        #   initialDelaySeconds: 30
        #   periodSeconds: 5
        # readinessProbe:
        #   httpGet:
        #     path: "/health"
        #     port: {{ .Values.containerPort }}
        #   initialDelaySeconds: 30
        #   periodSeconds: 5
        resources:
          requests:
            cpu: {{ .Values.requestCPU }}
            memory: {{ .Values.requestMemory }}
          limits:
            cpu: {{ .Values.limitCPU }}
            memory: {{ .Values.limitMemory }}
        env: 
        {{- range $key, $value := .Values.regularEnvData }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}

        {{- range $key, $value := .Values.secretData }}
        - name: {{ $key }}
          valueFrom: 
            secretKeyRef:
              name: {{ $.Values.secretName }}
              key: {{ $key }}
        {{- end }}

        {{- range $key, $value := .Values.configData }}
        - name: {{ $key }}
          valueFrom:
            configMapKeyRef:
              name: {{ $.Values.configName }}
              key: {{ $key }}
        {{- end }}
