apiVersion: apps/v1
kind: Deployment 
metadata:
  name: java-app
  labels:
    app: java-app 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app 
    spec:
      imagePullSecrets:
      - name: docker-authenticate
      containers:
      - name: java-app
        image: 565393037799.dkr.ecr.us-west-1.amazonaws.com/java-app:2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe: 
          httpGet:
            path: /health
            port: 8080
        env:
        - name: DB_USER
          valueFrom: 
            secretKeyRef:
              name: mysql-secret
              key: DB_USER
        - name: DB_PWD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: mysql-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_NAME
        - name: DB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mysql-configmap
              key: database_server

---
apiVersion: v1
kind: Service
metadata:
  name: java-app-service
spec:
  selector:
    app: java-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
