AppName: emailservice
ReplicaCount: 2
ImageName: gcr.io/google-samples/microservices-demo/emailservice
ImageVersion: v0.8.0
ContainerPort: 8080
ServicePort: 8080
ServiceType: ClusterIP
ContainerEnvVars: 
- name: PORT
  value: "8080"
- name: DISABLE_PROFILER
  value: "1"
RequestMemory: 64Mi
RequestCPU: 250m
LimitMemory: 128Mi
LimitCPU: 500m